services:
  app:
    container_name: myapp-php
    build: ./docker/php
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/
    depends_on:
      - db

  web:
    container_name: myapp-nginx
    image: nginx
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    container_name: myapp-mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    container_name: myapp-phpmyadmin
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    links:
      - db
    ports:
      - 8080:80
